# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Dolpirog' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dolpirog

     pod 'UITextView+Placeholder', '~> 1.2'




  target 'DolpirogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DolpirogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
