# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MapOfEurope' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapOfEurope

	pod 'SCLAlertView-Objective-C'

  target 'MapOfEuropeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapOfEuropeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
